server:
  port: 7100
spring:
  http:
    encoding.force: true
logging:
  level:
    root: info
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        # 测试使用 - 开放所有端口
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/