server:
  port: 7400
logging:
  level:
    root: info
    # 打印请求的Mapping映射信息
    #org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug
    # 打印Filter
    #org.springframework.cloud.gateway.handler.FilteringWebHandler: debug
    # 打印连接的整个流程信息
    #reactor.netty.resources.PooledConnectionProvider: debug
    # 打印请求的详细信息
    #reactor.netty.channel.ChannelOperationsHandler: debug
    # 打印重试信息
    reactor.retry.DefaultRetry: debug
    #org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: trace
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        # 测试使用 - 开放所有端口
        include: "*"
security:
  oauth2:
    client:
      clientId: oauth-common-client
      clientSecret: mysteel
      # client获取accessToken URI
      accessTokenUri: http://oauth.easycodebox.local:7500/oauth/token
      # 用户授权URI
      userAuthorizationUri: http://oauth.easycodebox.local:7500/oauth/authorize
      # 是否使用当前请求的uri最为redirect-uri，如果开启则优先于pre-established-redirect-uri。默认开启
      use-current-uri: false
      # 预定义redirect-uri
      pre-established-redirect-uri: "http://localhost:${server.port}/login"
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDGTdwymDuETEvshW9HIiUvLwMX
          WXXAebrh4IznaaLLMd0aUGNyiMHkf8YG99g/hJ5hVc9dGliDsQO4+Fmtfp/fwTY2
          7uCTelb9iVz3zloEICdG1Fk2a17SI6qvlUInaMGbIdq+8aPg/19edx3qoGamct6P
          /TaZ1pQEluaOAxGqQQIDAQAB
          -----END PUBLIC KEY-----
eureka:
  instance:
    prefer-ip-address: true
hystrix:
  command:
    # default配置全局HystrixCommand
    default:
      # 【注】Spring Cloud Gateway的execution.isolation.strategy默认使用SEMAPHORE
      # 配置HystrixCommand线程执行的超时时间，默认1000 - 自行调优
      execution.isolation.thread.timeoutInMilliseconds: 5000
      # 默认值10
      execution.isolation.semaphore.maxConcurrentRequests: 100
      # 默认值10
      fallback.isolation.semaphore.maxConcurrentRequests: 10
spring:
  http:
    encoding.force: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 网关路由时匹配service-id小写字母
          lower-case-service-id: true
          predicates:
          # 定义请求服务路径规则
          - Path='/'+serviceId+'/**'
          filters:
          # 去除path的serviceId前缀
          - RewritePath='/' + serviceId + '/(?<remaining>.*)', '/${remaining}'
          # 启用Hystrix
          - Hystrix=serviceId
          # 启用retry，需要放置在Hystrix后面。因Spring Cloud Gateway不能使用Ribbon的retry功能，只能使用此RetryGatewayFilter
          # 默认重试规则：1.GET请求 2.服务端返回的状态码为5xx 3.异常IOException或TimeoutException
          - Retry