server:
  port: 7300
spring:
  http:
    encoding.force: true
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        # 测试使用 - 开放所有端口
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
turbine:
  app-config: easycode-zuul,easycode-gateway,easycode-demo-org,easycode-demo-shop,easycode-demo-user
  aggregator:
    cluster-config: EASYCODE-ZUUL,EASYCODE-GATEWAY,EASYCODE-DEMO-ORG,EASYCODE-DEMO-SHOP,EASYCODE-DEMO-USER